/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorylinesRouteImport } from './routes/storylines'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorylineIdRouteImport } from './routes/storyline.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicCronRefreshRouteImport } from './routes/api/public/cron-refresh'

const StorylinesRoute = StorylinesRouteImport.update({
  id: '/storylines',
  path: '/storylines',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorylineIdRoute = StorylineIdRouteImport.update({
  id: '/storyline/$id',
  path: '/storyline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshRoute = ApiPublicCronRefreshRouteImport.update({
  id: '/api/public/cron-refresh',
  path: '/api/public/cron-refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/storylines': typeof StorylinesRoute
  '/api/chat': typeof ApiChatRoute
  '/event/$id': typeof EventIdRoute
  '/storyline/$id': typeof StorylineIdRoute
  '/api/public/cron-refresh': typeof ApiPublicCronRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/storylines': typeof StorylinesRoute
  '/api/chat': typeof ApiChatRoute
  '/event/$id': typeof EventIdRoute
  '/storyline/$id': typeof StorylineIdRoute
  '/api/public/cron-refresh': typeof ApiPublicCronRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/storylines': typeof StorylinesRoute
  '/api/chat': typeof ApiChatRoute
  '/event/$id': typeof EventIdRoute
  '/storyline/$id': typeof StorylineIdRoute
  '/api/public/cron-refresh': typeof ApiPublicCronRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/globe'
    | '/login'
    | '/signup'
    | '/social'
    | '/storylines'
    | '/api/chat'
    | '/event/$id'
    | '/storyline/$id'
    | '/api/public/cron-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/globe'
    | '/login'
    | '/signup'
    | '/social'
    | '/storylines'
    | '/api/chat'
    | '/event/$id'
    | '/storyline/$id'
    | '/api/public/cron-refresh'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/feed'
    | '/globe'
    | '/login'
    | '/signup'
    | '/social'
    | '/storylines'
    | '/api/chat'
    | '/event/$id'
    | '/storyline/$id'
    | '/api/public/cron-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  GlobeRoute: typeof GlobeRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  StorylinesRoute: typeof StorylinesRoute
  ApiChatRoute: typeof ApiChatRoute
  EventIdRoute: typeof EventIdRoute
  StorylineIdRoute: typeof StorylineIdRoute
  ApiPublicCronRefreshRoute: typeof ApiPublicCronRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storylines': {
      id: '/storylines'
      path: '/storylines'
      fullPath: '/storylines'
      preLoaderRoute: typeof StorylinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyline/$id': {
      id: '/storyline/$id'
      path: '/storyline/$id'
      fullPath: '/storyline/$id'
      preLoaderRoute: typeof StorylineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-refresh': {
      id: '/api/public/cron-refresh'
      path: '/api/public/cron-refresh'
      fullPath: '/api/public/cron-refresh'
      preLoaderRoute: typeof ApiPublicCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  GlobeRoute: GlobeRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  StorylinesRoute: StorylinesRoute,
  ApiChatRoute: ApiChatRoute,
  EventIdRoute: EventIdRoute,
  StorylineIdRoute: StorylineIdRoute,
  ApiPublicCronRefreshRoute: ApiPublicCronRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
